require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/expo/scripts/autolinking'

platform :ios, '15.1'
install! 'cocoapods', :deterministic_uuids => false

target 'HedgeFi' do
  use_expo_modules!
  config = use_native_modules!

  use_react_native!(
    :path => '../node_modules/react-native',
    :hermes_enabled => true
  )

  post_install do |installer|
    react_native_post_install(installer)
    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|
      target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
        resource_bundle_target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end

    installer.pods_project.targets.each do |target|
      if target.name == 'hermes-engine'
        target.build_configurations.each do |config|
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'HERMES_ENABLE=1'
        end
      end
      if target.name == 'fmt'
        target.build_configurations.each do |config|
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'FMT_NO_CHAR8_T=1'
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
          config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
        end
      end
      if target.name == 'glog'
        target.build_configurations.each do |config|
          config.build_settings['GCC_SUPPRESS_WARNINGS'] = 'YES'
        end
      end
    end
  end
end
